### ISSUE TITLE
interpret `transact_` inside IO monad

### ISSUE THREAD

**Issue by docteurklein** [haskell-haskey/haskey-mtl#5]
Hey there :) thank you for haskey, it looks super interesting!

I'm trying to use this lib in https://github.com/docteurklein/grap-hs/blob/main/src/Graphs.hs#L113
but I'm struggling like the beginner I am to understand how to make this piece of code work:

```haskell
app :: App ()
app = do
    insertSomeTriples
    printTriples
    conn <- ask
    liftIO $ BinLog.getLastBinLogTracker conn >>= \ case
        Just tracker -> do
            es <- BinLog.decodeRowBinLogEvent =<< BinLog.dumpBinLog conn 1024 tracker False
            forever $ do
                Streams.read es >>= \ case
                    Just (BinLog.RowWriteEvent _timestamp  _tracker table events)  ->
                        insertEvents []  -- events
                    Nothing -> return ()
        Nothing -> error "can't get latest binlog position"

insertEvents :: [BinLog.WriteRowsEvent] -> App ()
insertEvents events = transact_ $ \schema -> do
    foldlM insertTriple schema $ map e2t events
    commit_ schema
    where
        e2t (BinLog.WriteRowsEvent {writeRowData = d}) = Triple "a" "b" "c"

```

getting this error:

```
src/Graphs.hs:113:25: error:
    • Couldn't match type ‘App’ with ‘IO’
      Expected type: IO ()
        Actual type: App ()
    • In the expression: insertEvents []
      In a case alternative:
          Just (BinLog.RowWriteEvent _timestamp _tracker table events)
            -> insertEvents []
      In the second argument of ‘(>>=)’, namely
        ‘\case
           Just (BinLog.RowWriteEvent _timestamp _tracker table events)
             -> insertEvents []
           Nothing -> return ()’
    |
113 |                         insertEvents []  -- events
    |                         ^^^^^^^^^^^^^^^
Failed, no modules loaded.
λ
```

Does this have anything to do with the usage of MonadBaseControl ? I tried many variants of `liftBase` and such without success.
I guess it's more a problem with mtl than haskey per-se, but if you have any idea, I'm open to suggestions :)

Thanks in any case!

**Comment by Elland** [comment]
Hi there @docteurklein! Haskell type errors can be a bit daunting sometimes, especially when it sort of points you to the wrong place in the code. If you look a bit further up, you're using `Streams.read` and pattern matching on the result. The problem is that `read` returns [`IO (Maybe a)`](https://hackage.haskell.org/package/io-streams-1.5.2.1/docs/System-IO-Streams.html#v:read), and your function is constrained to the type `App ()`. 

I'm not too familiar with `haskey`, so it feels a bit odd answering an issue here, I hope you'll forgive me if I'm made some wrong assumptions about your code, but believe the most straight-forward solution to make the types match here, is to use `liftIO` to call `read`.

Best of luck!

**Comment by hsyl20** [comment]
>     liftIO $ BinLog.getLastBinLogTracker conn >>= \ case

With this, the whole `\case` expression is in the IO monad, not App. Try:

>     (liftIO $ BinLog.getLastBinLogTracker conn) >>= \ case

You'll have to use `liftIO` in a few other places, e.g.:

> es <- liftIO $ BinLog.decodeRowBinLogEvent =<< BinLog.dumpBinLog conn 1024 tracker False

**Comment by BrechtSerckx** [comment]
The problem lies in your `liftIO` call. The I believe you call `liftIO` because the `mysql-haskell` code lives in `IO`, but that means that every action in your `liftIO` argument also has to be `IO`, hindering your ability to do actions in the `App` monad later on (giving the error).

A solution would be to only call `liftIO` for the `IO` actions themselves:
```haskell
app :: App ()
app = do
    insertSomeTriples
    printTriples
    conn <- ask
    (liftIO $ BinLog.getLastBinLogTracker conn) >>= \ case
        Just tracker -> do
            es <- liftIO $  BinLog.decodeRowBinLogEvent =<< BinLog.dumpBinLog conn 1024 tracker False
            forever $ do
                liftIO (Streams.read es) >>= \ case
                    Just (BinLog.RowWriteEvent _timestamp  _tracker table events)  ->
                        insertEvents []  -- events
                    Nothing -> return ()
        Nothing -> error "can't get latest binlog position"
```

**Comment by docteurklein** [comment]
Amazing. Thanks for the pointer! I didn't think you could stop the liftIO call to propagate in the case expression.
Learning so much suff in haskell, it's great. 
Thank you so much!
